### ISSUE TITLE
Find free time

### ISSUE THREAD

**Issue by totoyoyo** [AY2021S2-CS2103-T16-2/tp#68]
Have command to find free time

freetime duration/HOURS startDate/START_DATE endDate/END_DATE dayOfWeek/{Mon,Tue,...} startTimeRange/{HH:MM} endTimeRange/{HH:MM}

Returns in the format:
  Found timeslots: 3
  starttime: …. endtime: .....
  starttime: …. endtime: .....
  starttime: …. endtime: .....

**Comment by Maurice2n97** [comment]
Find free time can be done via timetable
